### PR TITLE
v5 compat

### PR DESCRIPTION
**Pull request by TSMMark**
Not sure exactly what needs to be done to get a PR in here as there are no tests or guidelines but here is the crosstab persist I wrote for our app for v5. From conversation in #15 and https://github.com/rt2zz/redux-persist/issues/569

I’m using it like this:

```js
// @flow

import { applyMiddleware, createStore } from 'redux'
import { persistCombineReducers, persistStore } from 'redux-persist'
import { routerMiddleware, routerReducer } from 'react-router-redux'
import createHistory from 'history/createBrowserHistory'
import logger from 'redux-logger'
import persistCrosstab from './persistCrosstab'
import reducers from '../reducers'
import storage from 'redux-persist/es/storage'
import type { PersistConfig, Persistor } from 'redux-persist/es/types'
import type { Store } from 'redux'

export const history: History = createHistory()

const persistConfig: PersistConfig = {
  key: 'root',
  storage,
  whitelist: ['ui'], // Reducers to persist in localstorage.
}

const store: Store = createStore(
  persistCombineReducers(persistConfig, {
    ...reducers,
    router: routerReducer,
  }),
  applyMiddleware(logger, routerMiddleware(history))
)

export const persistor: Persistor = persistStore(store, undefined, () => {
  // `store.getState()` becomes available in this callback.
})

persistCrosstab(store, persistConfig, {
  whitelist: ['ui'], // Reducers to persist crosstab.
})

export default store
```

### CODE REVIEW

**Comment by rt2zz** [comment]
This looks great. It seems to make this fully functional we will need to import the deserialize + transforms process from redux-persist. This is not currently exported but it could be.

**Comment by TSMMark** [comment]
@rt2zz alright, are you thinking it's as simple as 

 1. Export `defaultDeserialize` as a named export from here https://github.com/rt2zz/redux-persist/blob/e92def2bfd819218cce4e0e03c0dbd149c56afc8/src/getStoredState.js#L41
 1. Use config.serialize if provided, or fall back to the newly-exported default if none provided

Other questions:

 1. Why does the state get double-serialized? Am I wrong, or does each reducer get serialized, then the root reducer gets serialized on top of that?
 1. Do I use the same deserialize for the root reducer and the combined reducers? Essentially everywhere in this PR where I use `JSON.parse`, just swap that out with `deserialize`, or is it more intricate than that?

**Comment by TSMMark** [comment]
@rt2zz If you merge https://github.com/rt2zz/redux-persist/pull/620 and ship a release I can finish this up in no time

**Comment by TSMMark** [comment]
bump

**Comment by TSMMark** [comment]
@rt2zz ?

**Comment by saeedezzati** [comment]
What's the status of this?

**Comment by TSMMark** [comment]
@markopol0 It's ready to go I'm just waiting on a maintainer for merges. @rt2zz I hope you're okay my dude!

**Comment by Cretezy** [comment]
Can confirm this works. The README should be updated with the new usage:

```js
crosstabSync(store, persistorConfig, crosstabConfig);
```

Another point to add would be that this only works with localStorage, and not others like localForage.

**Comment by avin** [comment]
Is it compatible with transformers like https://github.com/rt2zz/redux-persist-transform-immutable ?

I think it should be added

```
                if (blacklist && blacklist.indexOf(reducerKey) !== -1) {
                    return state;
                }

                state[reducerKey] = JSON.parse(statePartial[reducerKey]);

                //+++
                persistConfig.transforms && persistConfig.transforms.forEach(transform => {
                    state[reducerKey] = transform.out(state[reducerKey]);
                });

                return state;
            }, {});
```

**Comment by damianobarbati** [comment]
@TSMMark thanks for the effort!  @rt2zz is this making it into master anytime soon? 🙏🏻

**Comment by jadennnn** [comment]
@rt2zz would be great to get `redux-persist` v5 support!

**Comment by TSMMark** [comment]
Can we get a merge please?

**Comment by johnnyoshika** [comment]
Agreed! Merge would be really nice. :-)

**Comment by mbalabash** [comment]
@rt2zz 
Can we get a merge please?

**Comment by rt2zz** [comment]
Hi all, sorry for the slowness here, cutting a next release now. Please confirm if this is working for you if we get a couple of 👍 I will do a proper release

**Comment by rt2zz** [comment]
`4.0.0-0` out now under next tag
`npm i --save redux-persist@next`

**Comment by ignatiusreza** [comment]
was trying this out and got an error because of flow type.. i opened #21 to remove them, since we can't assume that end user will have flow type as part of their build process..

**Pull request merged**
